### ISSUE TITLE
Share requirements.txt file for this repo

### ISSUE THREAD

**Issue by Tushar-ml** [sayakpaul/diffusers-torchao#24]
Hi @sayakpaul , could you please share requirements file, as they are some dependency issues, like this
'FakeTensor' object has no attribute '_quantized_linear_op'

**Comment by sayakpaul** [comment]
You should be able to use it with `torch` nightly and `torchao` installed from the source. Since these change frequently, didn't think to make a `requirements.txt`. If the import problem is stemming from torch or torchao, you should open an issue on those repositories. 

For other dependencies, 

```
pip install diffusers transformers accelerate tabulate sentencepiece
```

Sorry for the inconvenience.
